Added codecov (#161)
* Added Codecov.

* Fixed a bug for Python test.

* Added the Codecov badge.

* Combined the C++ and python code coverage test.

* Separate C++ and python codecov uploads.

* Tested in Docker.

* Minor fix.

* Added the token.

* Added coverage xml.

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -24,17 +24,29 @@ function runTests()
 {
   rm -rf input DAFoam_Test_${1}.txt
   tar -zxf input.tar.gz
-  mpirun -np 4 python runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
-  if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
-    echo "${1}: Failed!"
-    exit 1
-  fi
-  python testFuncs.py refs/DAFoam_Test_${1}Ref.txt DAFoam_Test_${1}.txt
-  if [ "$?" -ne "0" ]; then 
-    echo "${1}: Failed!"
-    exit 1
+  if [ -z "$DF_CHECK_COVERAGE" ]; then
+    mpirun -np 4 python runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
+    python testFuncs.py refs/DAFoam_Test_${1}Ref.txt DAFoam_Test_${1}.txt
+    if [ "$?" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    else
+      echo "${1}: Success!"
+    fi
+  elif [ "$DF_CHECK_COVERAGE" = "1" ]; then
+    mpirun -np 4 coverage run runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
+    echo "DF_CHECK_COVERAGE key found! Do NOT check the regression test values!"
   else
-    echo "${1}: Success!"
+    echo "DF_CHECK_COVERAGE key not valid! Set it to 1!"
+    exit 1
   fi
 }
 
@@ -124,8 +136,10 @@ case $argm in
   "forward")
     echo "Running forward AD tests...."
     sleep 3
-    runTests DASimpleFoamForwardAD
-    runTests DASimpleFoamFieldForwardAD
+    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleADF.so" ]; then
+      runTests DASimpleFoamForwardAD
+      runTests DASimpleFoamFieldForwardAD
+    fi
     echo " "
     echo "************************************************************"
     echo "**************** Forward AD tests passed! ******************"
@@ -138,5 +152,3 @@ case $argm in
     exit 1
     ;;
 esac
-
-
