Fix v2 (#56)
* Changed the coveralls badge.

* Added Cython in setup.py.

* Updated test to cover cell state ordering.

* Updatd travis.

* Updated tests.

* Updated tests and travis.

* Updated tests.

* Updated tests and improve coverage.

* Updated tests and deleted unused functions in pyDAFoam.py.

* Delete an unused function in DAUtility.

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -5,6 +5,7 @@ if [ -z "$WM_PROJECT" ]; then
   exit 1
 fi
 
+# check if we need to download input.tar.gz
 if [ -f "input.tar.gz" ]; then
   echo "input.tar.gz already exists."
 else
@@ -12,52 +13,53 @@ else
   wget https://github.com/dafoam/files/releases/download/v1.0.0/input.tar.gz --no-check-certificate
 fi
 
-# test DAFoamIncompresible lib
-rm -rf input
-tar -zxf input.tar.gz
-cd input/CurvedCubeHexMesh && cp -r 0.incompressible/* 0/ && decomposePar
-cd ../../
-
-cd DAFoamIncompressible && make && mpirun --use-hwthread-cpus -np 4 python runTests.py || exit 1
-echo "DAFoamIncompressible: Success!"
-cd ../
-
-# test DAFoamCompressible lib
-rm -rf input
-tar -zxf input.tar.gz
-cd input/CurvedCubeHexMesh && cp -r 0.compressible/* 0/ && decomposePar
-cd ../../
-
-cd DAFoamCompressible && make && mpirun --use-hwthread-cpus -np 4 python runTests.py || exit 1
-echo "DAFoamCompressible: Success!"
-cd ../
-
 # test DASimpleFoam
-rm -rf input
+rm -rf input DAFoam_Test_DASimpleFoam.txt
 tar -zxf input.tar.gz
-
-cd pyDAFoam && mpirun --use-hwthread-cpus -np 4 python runTests_DASimpleFoam.py 2>&1 | tee DAFoam_Test_DASimpleFoam.txt
-python testFuncs.py refs/DAFoam_Test_DASimpleFoamRef.txt DAFoam_Test_DASimpleFoam.txt || exit 1
-echo "DASimpleFoam: Success!"
-cd ../
+mpirun -np 4 python runTests_DASimpleFoam.py $@ | tee DAFoam_Test_DASimpleFoam.txt 
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+  echo "DASimpleFoam: Failed!"
+  exit 1
+fi
+python testFuncs.py refs/DAFoam_Test_DASimpleFoamRef.txt DAFoam_Test_DASimpleFoam.txt
+if [ "$?" -ne "0" ]; then 
+  echo "DASimpleFoam: Failed!"
+  exit 1
+else
+  echo "DASimpleFoam: Success!"
+fi
 
 # test DARhoSimpleFoam
-rm -rf input
+rm -rf input DAFoam_Test_DARhoSimpleFoam.txt
 tar -zxf input.tar.gz
-
-cd pyDAFoam && mpirun --use-hwthread-cpus -np 4 python runTests_DARhoSimpleFoam.py 2>&1 | tee DAFoam_Test_DARhoSimpleFoam.txt
-python testFuncs.py refs/DAFoam_Test_DARhoSimpleFoamRef.txt DAFoam_Test_DARhoSimpleFoam.txt || exit 1
-echo "DARhoSimpleFoam: Success!"
-cd ../
+mpirun -np 4 python runTests_DARhoSimpleFoam.py $@ | tee DAFoam_Test_DARhoSimpleFoam.txt
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+  echo "DARhoSimpleFoam: Failed!"
+  exit 1
+fi
+python testFuncs.py refs/DAFoam_Test_DARhoSimpleFoamRef.txt DAFoam_Test_DARhoSimpleFoam.txt
+if [ "$?" -ne "0" ]; then 
+  echo "DARhoSimpleFoam: Failed!"
+  exit 1
+else
+  echo "DARhoSimpleFoam: Success!"
+fi
 
 # test DARhoSimpleCFoam
-rm -rf input
+rm -rf input DAFoam_Test_DARhoSimpleCFoam.txt
 tar -zxf input.tar.gz
-
-cd pyDAFoam && mpirun --use-hwthread-cpus -np 4 python runTests_DARhoSimpleCFoam.py 2>&1 | tee DAFoam_Test_DARhoSimpleCFoam.txt
-python testFuncs.py refs/DAFoam_Test_DARhoSimpleCFoamRef.txt DAFoam_Test_DARhoSimpleCFoam.txt || exit 1
-echo "DARhoSimpleCFoam: Success!"
-cd ../
+mpirun -np 4 python runTests_DARhoSimpleCFoam.py $@ | tee DAFoam_Test_DARhoSimpleCFoam.txt
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+  echo "DARhoSimpleCFoam: Failed!"
+  exit 1
+fi
+python testFuncs.py refs/DAFoam_Test_DARhoSimpleCFoamRef.txt DAFoam_Test_DARhoSimpleCFoam.txt
+if [ "$?" -ne "0" ]; then 
+  echo "DARhoSimpleCFoam: Failed!"
+  exit 1
+else
+  echo "DARhoSimpleCFoam: Success!"
+fi
 
 echo " "
 echo "************************************************************"
