Added a unitTest for pimpleDym.

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -52,7 +52,11 @@ function runRegTests()
 function runUnitTests()
 {
   rm -rf DAFoam_Test_${1}.txt
-  mpirun --oversubscribe -np 4 python runUnitTests_${1}.py
+  mpirun --oversubscribe -np 4 python runUnitTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+  if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+    echo "${1}: Failed!"
+    exit 1
+  fi
 }
 
 # Find all files matching the regression test script pattern
