Updated tests and improve coverage.

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -16,23 +16,50 @@ fi
 # test DASimpleFoam
 rm -rf input DAFoam_Test_DASimpleFoam.txt
 tar -zxf input.tar.gz
-mpirun -np 4 python runTests_DASimpleFoam.py 2>&1 | tee DAFoam_Test_DASimpleFoam.txt
-python testFuncs.py refs/DAFoam_Test_DASimpleFoamRef.txt DAFoam_Test_DASimpleFoam.txt || exit 1
-echo "DASimpleFoam: Success!"
+mpirun -np 4 python runTests_DASimpleFoam.py $@ | tee DAFoam_Test_DASimpleFoam.txt 
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+  echo "DASimpleFoam: Failed!"
+  exit 1
+fi
+python testFuncs.py refs/DAFoam_Test_DASimpleFoamRef.txt DAFoam_Test_DASimpleFoam.txt
+if [ "$?" -ne "0" ]; then 
+  echo "DASimpleFoam: Failed!"
+  exit 1
+else
+  echo "DASimpleFoam: Success!"
+fi
 
 # test DARhoSimpleFoam
 rm -rf input DAFoam_Test_DARhoSimpleFoam.txt
 tar -zxf input.tar.gz
-mpirun -np 4 python runTests_DARhoSimpleFoam.py 2>&1 | tee DAFoam_Test_DARhoSimpleFoam.txt
-python testFuncs.py refs/DAFoam_Test_DARhoSimpleFoamRef.txt DAFoam_Test_DARhoSimpleFoam.txt || exit 1
-echo "DARhoSimpleFoam: Success!"
+mpirun -np 4 python runTests_DARhoSimpleFoam.py $@ | tee DAFoam_Test_DARhoSimpleFoam.txt
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+  echo "DARhoSimpleFoam: Failed!"
+  exit 1
+fi
+python testFuncs.py refs/DAFoam_Test_DARhoSimpleFoamRef.txt DAFoam_Test_DARhoSimpleFoam.txt
+if [ "$?" -ne "0" ]; then 
+  echo "DARhoSimpleFoam: Failed!"
+  exit 1
+else
+  echo "DARhoSimpleFoam: Success!"
+fi
 
 # test DARhoSimpleCFoam
 rm -rf input DAFoam_Test_DARhoSimpleCFoam.txt
 tar -zxf input.tar.gz
-mpirun -np 4 python runTests_DARhoSimpleCFoam.py 2>&1 | tee DAFoam_Test_DARhoSimpleCFoam.txt
-python testFuncs.py refs/DAFoam_Test_DARhoSimpleCFoamRef.txt DAFoam_Test_DARhoSimpleCFoam.txt || exit 1
-echo "DARhoSimpleCFoam: Success!"
+mpirun -np 4 python runTests_DARhoSimpleCFoam.py $@ | tee DAFoam_Test_DARhoSimpleCFoam.txt
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+  echo "DARhoSimpleCFoam: Failed!"
+  exit 1
+fi
+python testFuncs.py refs/DAFoam_Test_DARhoSimpleCFoamRef.txt DAFoam_Test_DARhoSimpleCFoam.txt
+if [ "$?" -ne "0" ]; then 
+  echo "DARhoSimpleCFoam: Failed!"
+  exit 1
+else
+  echo "DARhoSimpleCFoam: Success!"
+fi
 
 echo " "
 echo "************************************************************"
