Combined the C++ and python code coverage test.

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -24,12 +24,12 @@ function runTests()
 {
   rm -rf input DAFoam_Test_${1}.txt
   tar -zxf input.tar.gz
-  mpirun -np 4 python runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
-  if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
-    echo "${1}: Failed!"
-    exit 1
-  fi
   if [ -z "$DF_CHECK_COVERAGE" ]; then
+    mpirun -np 4 python runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
     python testFuncs.py refs/DAFoam_Test_${1}Ref.txt DAFoam_Test_${1}.txt
     if [ "$?" -ne "0" ]; then 
       echo "${1}: Failed!"
@@ -38,6 +38,11 @@ function runTests()
       echo "${1}: Success!"
     fi
   elif [ "$DF_CHECK_COVERAGE" = "1" ]; then
+    mpirun -np 4 coverage run runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
     echo "DF_CHECK_COVERAGE key found! Do NOT check the regression test values!"
   else
     echo "DF_CHECK_COVERAGE key not valid! Set it to 1!"
