Added fixedPoint test. Totals not accurate yet.

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -49,6 +49,38 @@ function runRegTests()
   fi
 }
 
+function runSerialRegTests() 
+{
+  rm -rf DAFoam_Test_${1}.txt
+  if [ -z "$DF_CHECK_COVERAGE" ]; then
+    python runSerialRegTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
+    # need to replace the "[0m" for mphys tests 
+    sed -i 's/\[0m//g' DAFoam_Test_${1}.txt
+    sed -i 's/[^[:print:]\t]//g' DAFoam_Test_${1}.txt
+    python testFuncs.py refs/DAFoam_Test_${1}Ref.txt DAFoam_Test_${1}.txt
+    if [ "$?" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    else
+      echo "${1}: Success!"
+    fi
+  elif [ "$DF_CHECK_COVERAGE" = "1" ]; then
+    coverage run runSerialRegTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
+    echo "DF_CHECK_COVERAGE key found! Do NOT check the regression test values!"
+  else
+    echo "DF_CHECK_COVERAGE key not valid! Set it to 1!"
+    exit 1
+  fi
+}
+
 function runUnitTests()
 {
   rm -rf DAFoam_Test_${1}.txt
@@ -69,6 +101,19 @@ for file in runRegTests_*.py; do
     
     # run the regression tests
     runRegTests "$extracted_name"
+  fi
+done
+
+# Find all files matching the regression test script pattern
+for file in runSerialRegTests_*.py; do
+  # Check if the file exists to avoid wildcard issues
+  if [[ -f "$file" ]]; then
+    # Extract the part between "runSerialRegTests_" and ".py"
+    extracted_name="${file#runSerialRegTests_}"
+    extracted_name="${extracted_name%.py}"
+    
+    # run the regression tests
+    runSerialRegTests "$extracted_name"
   fi
 done
 
