Added tests for new solver and objectives.

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -29,6 +29,22 @@ else
   echo "DASimpleFoam: Success!"
 fi
 
+# test DASimpleTFoam
+rm -rf input DAFoam_Test_DASimpleTFoam.txt
+tar -zxf input.tar.gz
+mpirun -np 4 python runTests_DASimpleTFoam.py $@ | tee DAFoam_Test_DASimpleTFoam.txt 
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+  echo "DASimpleTFoam: Failed!"
+  exit 1
+fi
+python testFuncs.py refs/DAFoam_Test_DASimpleTFoamRef.txt DAFoam_Test_DASimpleTFoam.txt
+if [ "$?" -ne "0" ]; then 
+  echo "DASimpleTFoam: Failed!"
+  exit 1
+else
+  echo "DASimpleTFoam: Success!"
+fi
+
 # test DARhoSimpleFoam
 rm -rf input DAFoam_Test_DARhoSimpleFoam.txt
 tar -zxf input.tar.gz
@@ -43,6 +59,22 @@ if [ "$?" -ne "0" ]; then
   exit 1
 else
   echo "DARhoSimpleFoam: Success!"
+fi
+
+# test DARhoSimpleFoamUBend
+rm -rf input DAFoam_Test_DARhoSimpleFoamUBend.txt
+tar -zxf input.tar.gz
+mpirun -np 4 python runTests_DARhoSimpleFoamUBend.py $@ | tee DAFoam_Test_DARhoSimpleFoamUBend.txt
+if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+  echo "DARhoSimpleFoamUBend: Failed!"
+  exit 1
+fi
+python testFuncs.py refs/DAFoam_Test_DARhoSimpleFoamUBendRef.txt DAFoam_Test_DARhoSimpleFoamUBend.txt
+if [ "$?" -ne "0" ]; then 
+  echo "DARhoSimpleFoamUBend: Failed!"
+  exit 1
+else
+  echo "DARhoSimpleFoamUBend: Success!"
 fi
 
 # test DARhoSimpleCFoam
