Added more tracking files.

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -15,10 +15,37 @@ fi
 
 function runTests() 
 {
-  rm -rf reg_test_files-main
+  rm -rf reg_test_files-main DAFoam_Test_${1}.txt
   tar -zxf reg_test_files-main.tar.gz
-  mpirun --oversubscribe -np 4 python runTests_${1}.py 
+  if [ -z "$DF_CHECK_COVERAGE" ]; then
+    mpirun --oversubscribe -np 4 python runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
+    # need to replace the "[0m" for mphys tests 
+    sed -i 's/\[0m//g' DAFoam_Test_${1}.txt
+    sed -i 's/[^[:print:]\t]//g' DAFoam_Test_${1}.txt
+    python testFuncs.py refs/DAFoam_Test_${1}Ref.txt DAFoam_Test_${1}.txt
+    if [ "$?" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    else
+      echo "${1}: Success!"
+    fi
+  elif [ "$DF_CHECK_COVERAGE" = "1" ]; then
+    mpirun --oversubscribe -np 4 coverage run runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
+    echo "DF_CHECK_COVERAGE key found! Do NOT check the regression test values!"
+  else
+    echo "DF_CHECK_COVERAGE key not valid! Set it to 1!"
+    exit 1
+  fi
 }
+
 
 runTests DAUtility
 runTests DASimpleFoam
