latest from debug_solver

diff --git a/tests/Allrun b/tests/Allrun
--- a/tests/Allrun
+++ b/tests/Allrun
@@ -24,17 +24,29 @@ function runTests()
 {
   rm -rf input DAFoam_Test_${1}.txt
   tar -zxf input.tar.gz
-  mpirun -np 4 python runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
-  if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
-    echo "${1}: Failed!"
-    exit 1
-  fi
-  python testFuncs.py refs/DAFoam_Test_${1}Ref.txt DAFoam_Test_${1}.txt
-  if [ "$?" -ne "0" ]; then 
-    echo "${1}: Failed!"
-    exit 1
+  if [ -z "$DF_CHECK_COVERAGE" ]; then
+    mpirun -np 4 python runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
+    python testFuncs.py refs/DAFoam_Test_${1}Ref.txt DAFoam_Test_${1}.txt
+    if [ "$?" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    else
+      echo "${1}: Success!"
+    fi
+  elif [ "$DF_CHECK_COVERAGE" = "1" ]; then
+    mpirun -np 4 coverage run runTests_${1}.py $@ | tee DAFoam_Test_${1}.txt 
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then 
+      echo "${1}: Failed!"
+      exit 1
+    fi
+    echo "DF_CHECK_COVERAGE key found! Do NOT check the regression test values!"
   else
-    echo "${1}: Success!"
+    echo "DF_CHECK_COVERAGE key not valid! Set it to 1!"
+    exit 1
   fi
 }
 
@@ -43,22 +55,36 @@ case $argm in
     echo "Running all tests...."
     sleep 3
     runTests Integration
+    runTests Primal
     runTests DASimpleFoam
-    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleAD.so" ]; then
+    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleADR.so" ]; then
       runTests DASimpleFoamAD
       runTests DASimpleFoamField
+      runTests DASimpleFoamkOmegaFieldInversionOmega
+    fi
+    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleADF.so" ]; then
+      runTests DASimpleFoamForwardAD
+      runTests DASimpleFoamFieldForwardAD
     fi
     runTests DASimpleFoamMRF
     runTests DASimpleTFoam
     runTests DAPisoFoam
     runTests DAPisoFoamACTL
+    runTests DAPimpleFoam
+    runTests DAPimpleDyMFoam
     runTests DARhoSimpleFoam
     runTests DARhoSimpleFoamMRF
     runTests DARhoSimpleFoamUBend
     runTests DARhoSimpleCFoam
+    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleADR.so" ]; then
+      runTests DARhoSimpleFoamAD
+      runTests DARhoSimpleCFoamAD
+    fi
     runTests DATurboFoamSubsonic
     runTests DATurboFoamTransonic
     runTests DASolidDisplacementFoam
+    runTests DAScalarTransportFoam
+    runTests DALaplacianFoam
     echo " "
     echo "************************************************************"
     echo "**************** All DAFoam tests passed! ******************"
@@ -69,8 +95,9 @@ case $argm in
     echo "Running incompressible tests...."
     sleep 3
     runTests Integration
+    runTests Primal
     runTests DASimpleFoam
-    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleAD.so" ]; then
+    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleADR.so" ]; then
       runTests DASimpleFoamAD
       runTests DASimpleFoamField
     fi
@@ -78,6 +105,8 @@ case $argm in
     runTests DASimpleTFoam
     runTests DAPisoFoam
     runTests DAPisoFoamACTL
+    runTests DAPimpleFoam
+    runTests DAPimpleDyMFoam
     echo " "
     echo "************************************************************"
     echo "************** Incompressible tests passed! ****************"
@@ -91,6 +120,10 @@ case $argm in
     runTests DARhoSimpleFoamMRF
     runTests DARhoSimpleFoamUBend
     runTests DARhoSimpleCFoam
+    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleADR.so" ]; then
+      runTests DARhoSimpleFoamAD
+      runTests DARhoSimpleCFoamAD
+    fi
     runTests DATurboFoamSubsonic
     runTests DATurboFoamTransonic
     echo " "
@@ -103,17 +136,30 @@ case $argm in
     echo "Running solid tests...."
     sleep 3
     runTests DASolidDisplacementFoam
+    runTests DAScalarTransportFoam
+    runTests DALaplacianFoam
     echo " "
     echo "************************************************************"
     echo "******************* Solid tests passed! ********************"
     echo "************************************************************"
     echo " "
     ;;
+  "forward")
+    echo "Running forward AD tests...."
+    sleep 3
+    if [ -f "$DAFOAM_ROOT_PATH/OpenFOAM/sharedLibs/libDAFoamIncompressibleADF.so" ]; then
+      runTests DASimpleFoamForwardAD
+      runTests DASimpleFoamFieldForwardAD
+    fi
+    echo " "
+    echo "************************************************************"
+    echo "**************** Forward AD tests passed! ******************"
+    echo "************************************************************"
+    echo " "
+    ;;
   *)
-    echo "Argument not valid! Options are: all, incompressible, compressible, or solid"
+    echo "Argument not valid! Options are: all, incompressible, compressible, solid, or forward"
     echo "Example: ./Allrun all"
     exit 1
     ;;
 esac
-
-
